export const ACTION_TYPES = {
    SET_CARDS: 'SET_CARDS',
    SET_READING_MODE: 'SET_READING_MODE',
    CHANGE_FILTER: 'CHANGE_FILTER',
    LIKE_CARD: 'LIKE_CARD',
    DISLIKE_CARD: 'DISLIKE_CARD',
    SEARCH_CARD: 'SEARCH_CARD',
} as const