export const EMOJIS = {
    LOGO: '⚛',
    HOME: '🏠',
    READ: '👁️',
    TRAINING: '‍🎓',
    ADD: '📝',
    SETTINGS: '⚙️',
    LIKE: '👍',
    DISLIKE: '👎',
    COMMENTS: '💬',
    FAVORITE: '🧡',
    UNFAVORITE: '💔',
    VIEW: '👀',
    COPY: '📋',
    CLOSE: '🔼',
    OPEN: '🔽',
    UP: '▲',
    DOWN: '▼',
    STOP: '🧱',
    CANCEL: '❌',
    SEARCH: '🔍',
} as const