export const RENDERS = {
    APP: 'Render App',
    BACKGROUND: 'Render Background',
    BUTTON: 'Render Button',
    BUTTON_ICON: 'Render ButtonIcon: ',
    CARD: 'Render Card: ',
    CARD_DETAILS: 'Render CardDetails: ',
    COLOR_BACKGROUND: 'Render ColorBackground',
    CREATE_CARD: 'Render CreateCard',
    DASHBOARD: 'Render Dashboard',
    ERROR_404: 'Render Error404',
    HEADER: 'Render Header',
    OVERLAY: 'Render Overlay',
    SELECT: 'Render Select: ',
    SPOILER_TEXT: 'Render SpoilerText',
    VIDEO_BACKGROUND: 'Render VideoBackground',
    WALLPAPER_BACKGROUND: 'Render WallpaperBackground',
} as const