import {EMOJIS} from './emojis'

export const STRINGS = {
    EMPTY: '',
    COMMA_SPACE_DELIMITER: ', ',
    COMMA_SEPARATOR: ',',
    TAGS: 'Tags',
    ALL: 'ALL',
    UNCATEGORIZED: 'Uncategorized',
    REACT: 'React',
    JAVASCRIPT: 'JavaScript',
    HTML: 'HTML',
    CSS: 'CSS',
    OPTIONAL: '(optional)',
    NAME: 'Name',
    EMAIL: 'Email',
    CARD_TITLE: 'Card title',
    CARD_CATEGORY: 'Card category',
    CARD_CONTENT: 'Card content',
    CREATE: 'Create',
    CREATE_CARD: 'Create card',
    CARD_CREATED: 'Card created',
    CARD_SENT: 'Card created and sent for review. It will be on the dashboard soon. Thanks for contributing! 🤝',
    CREATE_MORE: 'Create more',
    TO_DASHBOARD: 'Back to dashboard',
    CARD_ADDED: 'Card added: ',
    CARD_SEARCH: 'Card search...',
    ALPHABET_ASCENDING: `${EMOJIS.ASCENDING} Alphabet`,
    ALPHABET_DESCENDING: `${EMOJIS.DESCENDING} Alphabet`,
    LIKES_ASCENDING: `${EMOJIS.ASCENDING} Likes`,
    LIKES_DESCENDING: `${EMOJIS.DESCENDING} Likes`,
    DISLIKES_ASCENDING: `${EMOJIS.ASCENDING} Dislikes`,
    DISLIKES_DESCENDING: `${EMOJIS.DESCENDING} Dislikes`,
    COMMENTS_ASCENDING: `${EMOJIS.ASCENDING} Comments`,
    COMMENTS_DESCENDING: `${EMOJIS.DESCENDING} Comments`,
    ONLINE: 'Internet connection is restored. App is online. Loaded actual cards from server.',
    LOADED: 'Cards loaded from server: ',
    UPDATED: 'Cards updated from server: ',
    VIEW: 'View',
    VIEW_ALL: 'View all',
    UNVIEW: 'Unview',
    UNVIEW_ALL: 'Unview all',
    DELETE: 'Delete',
    CLEAR_ALL: 'Clear all',
    ENGLISH: 'English',
    RUSSIAN: 'Russian',
    COLOR: 'Color',
    WALLPAPER: 'Wallpaper',
    RANDOM_WALLPAPER: 'Random wallpaper',
    VIDEO: 'Video',
    OVERLAY: 'Overlay',
    WHITE: {NAME: 'White', COLOR: '#fff'},
    WARM: {NAME: 'Warm', COLOR: 'antiquewhite'},
    RED: {NAME: 'Red', COLOR: 'darkred'},
    GREEN: {NAME: 'Green', COLOR: 'green'},
    BLUE: {NAME: 'Blue', COLOR: 'midnightblue'},
    PURPLE: {NAME: 'Purple', COLOR: 'rebeccapurple'},
    GRAY: {NAME: 'Gray', COLOR: 'slategray'},
    BLACK: {NAME: 'Black', COLOR: 'black'},
    WALLPAPER1: 'Bliss',
    WALLPAPER2: 'The Persistence of Memory',
    WALLPAPER3: 'The Last Supper',
    WALLPAPER4: 'Morning in a Pine Forest',
    BEACH: 'Beach',
    OCEAN: 'Ocean',
    FIREPLACE: 'Fireplace',
    MOTIVATE: 'Motivate',
    LIFT: 'Lift',
    PAIN: 'Pain',
    RAIN: 'Rain',
    HALF_MINUTE: '30 seconds',
    MINUTE: '1 minute',
    TEN_MINUTES: '10 minutes',
    GENERAL: 'General',
    NOTIFICATION_SOUND: 'Play notification sound: ',
    LANGUAGE: 'Language: ',
    DASHBOARD: 'Dashboard',
    AUTO_UPDATE: 'Auto-update cards from server in background: ',
    AUTO_UPDATE_INTERVAL: 'Update cards every: ',
    CARDS_WARNING: 'Show custom cards warning: ',
    BACKGROUND: 'Background',
    BACKGROUND_TYPE: 'Background type: ',
    BACKGROUND_COLOR: 'Background color: ',
    BACKGROUND_WALLPAPER: 'Background wallpaper: ',
    BACKGROUND_VIDEO: 'Background video: ',
    BACKGROUND_OVERLAY: 'Background overlay (50% darker): ',
    BACKGROUND_SOUND: 'Play video background sound (if available): ',
    ABOUT: 'About',
    VERSION: 'Version: ',
    BUILD: 'Build: ',
    GITHUB: 'GitHub: ',
    DEDICATED: 'For learners by learner',
    RESET: 'Reset',
    CLEAR_SESSION_CACHE: 'Clear session cache',
    CLEAR_LOCAL_CACHE: 'Clear local cache',
    CLEAR_ALL_CACHE: 'Clear all cache',
    RESET_SETTINGS: 'Reset settings to default',
    DEVELOPER: 'Developer',
    DEVELOPER_MODE: 'Developer mode: ',
    LOG_RENDER: 'Log component rendering to console: ',
    SHOW_MARKUP: 'Show markup: ',
} as const

export const PROJECT = {
    NAME: 'Webatoria',
    DESCRIPTION: 'is a card-based app for learning web development and preparing for job interviews',
    SLOGAN: 'Web abyss to learning bliss',
    VERSION: '0.1 alpha',
    BUILD: '230424',
    COPYRIGHT: '\'24',
} as const