export const STRINGS = {
    EMPTY: '',
    COMMA_SPACE_DELIMITER: ', ',
    TAGS: 'Tags',
    ALL: 'ALL',
    UNCATEGORIZED: 'Uncategorized',
    REACT: 'React',
    JAVASCRIPT: 'JavaScript',
    HTML: 'HTML',
    CSS: 'CSS',
    OPTIONAL: '(optional)',
    NAME: 'Name',
    EMAIL: 'Email',
    CARD_TITLE: 'Card title',
    CARD_CATEGORY: 'Card category',
    CARD_CONTENT: 'Card content',
    CREATE: 'Create',
    CREATE_CARD: 'Create card',
    CARD_CREATED: 'Card created',
    CARD_SENT: 'Card created and sent for review. It will be on the dashboard soon. Thanks for contributing! 🤝',
    CREATE_MORE: 'Create more',
    TO_DASHBOARD: 'Back to dashboard',
} as const