import {EMOJIS} from './emojis'

export const STRINGS = {
    EMPTY: '',
    COMMA_SPACE_DELIMITER: ', ',
    COMMA_SEPARATOR: ',',
    TAGS: 'Tags',
    ALL: 'ALL',
    UNCATEGORIZED: 'Uncategorized',
    REACT: 'React',
    JAVASCRIPT: 'JavaScript',
    HTML: 'HTML',
    CSS: 'CSS',
    OPTIONAL: '(optional)',
    NAME: 'Name',
    EMAIL: 'Email',
    CARD_TITLE: 'Card title',
    CARD_CATEGORY: 'Card category',
    CARD_CONTENT: 'Card content',
    CREATE: 'Create',
    CREATE_CARD: 'Create card',
    CARD_CREATED: 'Card created',
    CARD_SENT: 'Card created and sent for review. It will be on the dashboard soon. Thanks for contributing! 🤝',
    CREATE_MORE: 'Create more',
    TO_DASHBOARD: 'Back to dashboard',
    CARD_ADDED: 'Card added: ',
    CARD_SEARCH: 'Card search...',
    ALPHABET_ASCENDING: `${EMOJIS.ASCENDING} Alphabet`,
    ALPHABET_DESCENDING: `${EMOJIS.DESCENDING} Alphabet`,
    LIKES_ASCENDING: `${EMOJIS.ASCENDING} Likes`,
    LIKES_DESCENDING: `${EMOJIS.DESCENDING} Likes`,
    DISLIKES_ASCENDING: `${EMOJIS.ASCENDING} Dislikes`,
    DISLIKES_DESCENDING: `${EMOJIS.DESCENDING} Dislikes`,
    COMMENTS_ASCENDING: `${EMOJIS.ASCENDING} Comments`,
    COMMENTS_DESCENDING: `${EMOJIS.DESCENDING} Comments`,
    ONLINE: 'Internet connection is restored. App is online. Loaded actual cards from server.',
    LOADED: 'Cards loaded from server: ',
    VIEW: 'View',
    VIEW_ALL: 'View all',
    UNVIEW: 'Unview',
    UNVIEW_ALL: 'Unview all',
    DELETE: 'Delete',
    CLEAR_ALL: 'Clear all',
} as const